### ISSUE TITLE
HVV/GeoFox authentication

### ISSUE THREAD

**Issue by georg90** [3wille/PebbleHVV#1]
Hi!

I like your implementation and like to port this to node.js

Since I'm trying for a while now and can't get the authentication to work, I would like to ask if this version is still working?

E.g. I use a different url to communicate with the API.. 

```
function Test(result)
{
    data = {
    "coordinateType": "EPSG_4326",
    "maxList": "1",
    "theName": {

        "name": "Informatikum",
        "type": "STATION"
    }

    };

    var Request = unirest.post('http://api-test.geofox.de/gti/public/checkName');

    Request.headers({'geofox-auth-user': 'username', 'geofox-auth-signature': 'signature'})
    .encoding('utf-8')
    .type('json')
    .send(data)
    .end(function (response) {
    console.log(response.body);
    });
}
```

I have a running implementation in python but the authentication headers are not properly set in node.js

Any help is appreciated.

**Comment by georg90** [comment]
Still interested in a solution :)

**Comment by 3wille** [comment]
Ohh hey @georg90 
Unfortunately I haven't seen your issue. I stopped working on this early last year and since April '15 my auth key is invalid. I am not up to date about the status of the geofox API and I have no experience in Node.js
From what you posted and what I wrote back than, the only difference is that you don't set the `geofox-auth-type` header

**Comment by georg90** [comment]
Don't worry about it :)
I figured it out - the auth didn't change much. Have a look at my implementation here:
https://github.com/georg90/MMM-HH-LocalTransport/blob/master/node_helper.js#L23-L31
